<a href="https://colab.research.google.com/github/kp2899990/komal-prasad-saini/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#part -> 1 numpy array basics

In [10]:
import numpy as np
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2],[3, 4]])
array_3d = np.array([[[1, 2],[3, 4],[5, 6],[7, 8]]])
print("1d_array:")
print("array:", array_1d)
print("shape:", array_1d.shape)
print("dimensions:", array_1d.ndim)
print("2d_array:")
print("array_2d:", array_2d)
print("shape:", array_2d.shape)
print("dimensions:", array_2d.ndim)
print("3d_array:")
print("array_3d:", array_3d)
print("shape:", array_3d.shape)
print("dimensions:", array_3d.ndim)

1d_array:
array: [1 2 3 4 5]
shape: (5,)
dimensions: 1
2d_array:
array_2d: [[1 2]
 [3 4]]
shape: (2, 2)
dimensions: 2
3d_array:
array_3d: [[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
shape: (1, 4, 2)
dimensions: 3


part2 -> indexing andf slicing

In [15]:
arr = np.array([10, 20, 30, 40, 50])
second_element = arr[1]
third_element = arr[2]
last_element = arr[-1]
print("second_element:", second_element)
print("third_element:", third_element)
print("last_element:", last_element)
sliced_array = arr[1:4]
print("sliced array[20, 30, 40]:", sliced_array)

second_element: 20
third_element: 30
last_element: 50
sliced array[20, 30, 40]: [20 30 40]


part3 -> array operations

In [18]:
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
addition = array_a + array_b
subtraction = array_a - array_b
multiplication = array_a * array_b
division = array_a / array_b
max_value = np.max(array_a)
min_value = np.min(array_a)
mean_value = np.mean(array_a)
std_deviation = np.std(array_a)
print("addition:", addition)
print("subtraction:", subtraction)
print("multplication:", multiplication)
print("division:", division)
print("max_value:", max_value)
print("min_value:", min_value)
print("mean_value:", mean_value)
print("std_deviation:", std_deviation)

addition: [5 7 9]
subtraction: [-3 -3 -3]
multplication: [ 4 10 18]
division: [0.25 0.4  0.5 ]
max_value: 3
min_value: 1
mean_value: 2.0
std_deviation: 0.816496580927726


Matrix operations

In [21]:
matrix_2d = np.array([[1, 2],[3, 4]])
transpose_matrix = np.transpose(matrix_2d)
matrix_a = np.array([[1, 2],[3, 4]])
matrix_b = np.array([[5, 6],[7, 8]])
matrix_multiplication = np.dot(matrix_a, matrix_b)
print("2d_matrix:", matrix_2d)
print("transpose of 2d matrix:", transpose_matrix)
print("matrix multiplication result:", matrix_multiplication)

2d_matrix: [[1 2]
 [3 4]]
transpose of 2d matrix: [[1 3]
 [2 4]]
matrix multiplication result: [[19 22]
 [43 50]]


BROADCASTING

In [22]:
import numpy as np
array_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
array_1d = np.array([1, 2, 3, 4])
result = array_2d + array_1d

print("2D Array:\n", array_2d)
print("1D Array:\n", array_1d)
print("Result of Broadcasting:\n", result)


2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1D Array:
 [1 2 3 4]
Result of Broadcasting:
 [[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]


Fancing indexing


In [23]:
arr = np.array([5, 10, 15, 20, 25, 30])
fancy_indexed_elements = arr[[1, 3, 4]]

print("Array:", arr)
print("Extracted Elements:", fancy_indexed_elements)


Array: [ 5 10 15 20 25 30]
Extracted Elements: [10 20 25]


Boolean masking

In [24]:
random_array = np.random.randint(1, 51, size=10)
mask = random_array > 25
filtered_elements = random_array[mask]
print("Random Array:", random_array)
print("Elements Greater Than 25:", filtered_elements)


Random Array: [ 9 29 19 15 34  7 10 26 35  7]
Elements Greater Than 25: [29 34 26 35]


Sorting

In [25]:
arr_to_sort = np.array([30, 10, 50, 20, 40])
ascending_order = np.sort(arr_to_sort)
descending_order = np.sort(arr_to_sort)[::-1]

print("Original Array:", arr_to_sort)
print("Sorted in Ascending Order:", ascending_order)
print("Sorted in Descending Order:", descending_order)


Original Array: [30 10 50 20 40]
Sorted in Ascending Order: [10 20 30 40 50]
Sorted in Descending Order: [50 40 30 20 10]
